version: "3"

services:
  alfresco1:
    image: 321006660882.dkr.ecr.eu-west-1.amazonaws.com/queres/alfresco-4.1:4.1.10.4
    hostname: alfresco1
    environment:
       DB_URL: 'jdbc:mysql://db:3306/alfresco?useUnicode=yes&characterEncoding=UTF-8'
       DB_PASSWORD: "bce280bb06"
       ALFRESCO_SOLR_HOST: "proxy"
       ALFRESCO_SOLR_PORT: "80"
       ALFRESCO_SOLR_PORT_SSL: "443"
       ALFRESCO_GLOBAL_PROPERTIES_1: "mail.host=mta"
       ALFRESCO_GLOBAL_PROPERTIES_6: "index.subsystem.name=solr"
       ALFRESCO_GLOBAL_PROPERTIES_1: "dir.keystore.custom=/opt/keystore/alfresco"
       ALFRESCO_GLOBAL_PROPERTIES_2: "encryption.ssl.keystore.location=$${dir.keystore.custom}/ssl.keystore_docker"
       ALFRESCO_GLOBAL_PROPERTIES_3: "encryption.ssl.keystore.keyMetaData.location=$${dir.keystore.custom}/ssl-keystore-passwords.properties"
       ALFRESCO_GLOBAL_PROPERTIES_4: "encryption.ssl.truststore.location=$${dir.keystore.custom}/ssl.truststore_docker"
       ALFRESCO_GLOBAL_PROPERTIES_5: "encryption.ssl.truststore.keyMetaData.location=$${dir.keystore.custom}/ssl-truststore-passwords.properties"
    links:
       - db
       - mta

  solr1:
    image: 321006660882.dkr.ecr.eu-west-1.amazonaws.com/queres/alfresco-solr-4.1:4.1.10.4
    hostname: solr1
    environment:
       SOLR_ALFRESCO_HOST: "proxy"
       SOLR_ALFRESCO_PORT: "80"
       SOLR_ALFRESCO_PORT_SSL: "443"

  db:
    image: mysql:5.6
    environment:
       MYSQL_ROOT_PASSWORD: b59bb4bcd4
       MYSQL_DATABASE: alfresco
       MYSQL_USER: alfresco
       MYSQL_PASSWORD: bce280bb06

  proxy:
    image: 321006660882.dkr.ecr.eu-west-1.amazonaws.com/queres/httpd-proxy-alfresco-alpine:1.0
    ports:
       - "90:80"
    environment:
       ALFRESCO_MEMBERS: "alfresco1"
       SOLR_MEMBERS: "solr1"
       
  mta:
    image: 321006660882.dkr.ecr.eu-west-1.amazonaws.com/queres/postfix-alpine:1.0
