version: "3"

services:
  alfresco1:
    image: 321006660882.dkr.ecr.eu-west-1.amazonaws.com/queres/alfresco-5.1:5.1.3.2
    hostname: alfresco1
    environment:
       DB_URL: "jdbc:mysql://db:3306/alfresco?useUnicode=yes&characterEncoding=UTF-8"
       DB_PASSWORD: "cd774a68ee"
       ALFRESCO_SOLR_HOST: "proxy"
       ALFRESCO_SOLR_PORT: "80"
       ALFRESCO_SOLR_PORT_SSL: "443"
       ALFRESCO_GLOBAL_PROPERTIES_1: "mail.host=mta"
    links:
       - db
       - mta
    volumes:
       - docroot:/opt/alf_data

  solr1:
    image: 321006660882.dkr.ecr.eu-west-1.amazonaws.com/queres/alfresco-solr4-5.1:5.1.3.2
    hostname: solr1
    environment:
       SOLR_ALFRESCO_HOST: "proxy"
       SOLR_ALFRESCO_PORT: "80"
       SOLR_ALFRESCO_PORT_SSL: "443"
    volumes:
       - index:/opt/index

  db:
    image: mysql:5.6
    environment:
       MYSQL_ROOT_PASSWORD: c366c28245
       MYSQL_DATABASE: alfresco
       MYSQL_USER: alfresco
       MYSQL_PASSWORD: cd774a68ee
    volumes:
       - mysqldb:/var/lib/mysql

  proxy:
    image: 321006660882.dkr.ecr.eu-west-1.amazonaws.com/queres/httpd-proxy-alfresco-alpine:1.0
    ports:
       - "90:80"
       - "9443:443"
    environment:
       ALFRESCO_MEMBERS: "alfresco1"
       SOLR_MEMBERS: "solr1"

  mta:
    image: 321006660882.dkr.ecr.eu-west-1.amazonaws.com/queres/postfix-alpine:1.0

volumes:
  docroot:
    driver: local
  index:
    driver: local
  mysqldb:
    driver: local
