version: "3"

services:
  alfresco1:
    image: 321006660882.dkr.ecr.eu-west-1.amazonaws.com/queres/alfresco-5.2:5.2.1
    hostname: alfresco1
    environment:
       DB_URL: "jdbc:mysql://db:3306/alfresco?useUnicode=yes&characterEncoding=UTF-8&useSSL=false"
       DB_PASSWORD: "3e0bd9b81d"
       ALFRESCO_SOLR_HOST: "proxy"
       ALFRESCO_SOLR_PORT: "80"
       ALFRESCO_HAZELCAST_PASSWORD: "testpass"
       ALFRESCO_GLOBAL_PROPERTIES_1: "mail.host=mta"
       ALFRESCO_GLOBAL_PROPERTIES_2: "index.subsystem.name=solr6"
       ALFRESCO_GLOBAL_PROPERTIES_3: "solr.secureComms=none"
       ALFRESCO_GLOBAL_PROPERTIES_4: "solr.port=80"
       ALFRESCO_GLOBAL_PROPERTIES_5: "solr.baseUrl=/solr"
    links:
       - db
       - mta
    volumes:
       - docroot:/opt/alf_data

  solr1:
    image: 321006660882.dkr.ecr.eu-west-1.amazonaws.com/queres/alfresco-solr6:1.1.0
    hostname: solr1
    environment:
       SOLR_ALFRESCO_HOST: "proxy"
       SOLR_ALFRESCO_PORT: "80"
    volumes:
       - index:/opt/index

  db:
    image: mysql:5.7.20
    environment:
       MYSQL_ROOT_PASSWORD: 39357ca8ed
       MYSQL_DATABASE: alfresco
       MYSQL_USER: alfresco
       MYSQL_PASSWORD: 3e0bd9b81d
    volumes:
       - mysqldb:/var/lib/mysql

  proxy:
    image: 321006660882.dkr.ecr.eu-west-1.amazonaws.com/queres/httpd-proxy-alfresco-alpine:2.0
    ports:
       - "90:80"
       - "9443:443"
    environment:
       ALFRESCO_MEMBERS: "alfresco1"
       SOLR_MEMBERS: "solr1"
       SOLR_PROTOCOL: "http"
       SOLR_PROTOCOL_PORT: "8983"

  mta:
    image: 321006660882.dkr.ecr.eu-west-1.amazonaws.com/queres/postfix-alpine:1.0

volumes:
  docroot:
    driver: local
  mysqldb:
    driver: local
  index:
    driver: local
