version: "3"

services:
  alfresco1:
    image: 321006660882.dkr.ecr.eu-west-1.amazonaws.com/queres/alfresco-5.1:5.1.3.2
    hostname: alfresco1
    environment:
       DB_URL: "jdbc:oracle:thin:@oracle.queres.loc:1521:XE"
       DB_USERNAME: "alfresco1des"
       DB_PASSWORD: "alfresco1des"
       DB_DRIVER: "oracle.jdbc.OracleDriver"
       HIBERNATE_DEFAULT_SCHEMA: "ALFRESCO1DES"
       DB_POOL_VALIDATE_QUERY: "SELECT 1 FROM DUAL"
       ALFRESCO_HAZELCAST_PASSWORD: "cluster_alfresco_2548136475"
       ALFRESCO_EAGERORPHANCLEANUP: "true"
       ALFRESCO_ORPHANPROTECTDAYS: "1"
       ALFRESCO_DIR_SHARED: "/mnt/alfresco1/compartido/alf_data"
       ALFRESCO_GLOBAL_PROPERTIES_1: "version.store.enableAutoVersionOnUpdateProps=true"
       ALFRESCO_GLOBAL_PROPERTIES_2: "img.gslib=/usr/share/ghostscript/9.07/lib"
       ALFRESCO_GLOBAL_PROPERTIES_3: "vgss.haltOnError=false"
       ALFRESCO_SOLR_HOST: "proxy"
       ALFRESCO_SOLR_PORT: "80"
       ALFRESCO_SOLR_PORT_SSL: "443"
       DISABLE_LICENSE: "true"
    volumes:
       - ./amps:/amps.d
       - ./shared-classes:/usr/local/tomcat/shared/classes
       - nfs_compartido:/mnt/alfresco1/compartido
       - nfs_sscc00:/mnt/alfresco1/compartido/sscc/volumen00000000
       - nfs_sscc01:/mnt/alfresco1/compartido/sscc/volumen00000001
       - nfs_sscc02:/mnt/alfresco1/compartido/sscc/volumen00000002
       - nfs_sscc03:/mnt/alfresco1/compartido/sscc/volumen00000003
       - nfs_our00:/mnt/alfresco1/compartido/our/volumen00000000
       - nfs_eoxi_santiago00:/mnt/alfresco1/compartido/eoxi_santiago/volumen00000000
       - nfs_eoxi_santiago01:/mnt/alfresco1/compartido/eoxi_santiago/volumen00000001
       - nfs_eoxi_santiago02:/mnt/alfresco1/compartido/eoxi_santiago/volumen00000002
       - nfs_eoxi_santiago03:/mnt/alfresco1/compartido/eoxi_santiago/volumen00000003
       - nfs_hula00:/mnt/alfresco1/compartido/hula/volumen00000000
       - nfs_hula01:/mnt/alfresco1/compartido/hula/volumen00000001
       - nfs_chus00:/mnt/alfresco1/compartido/chus/volumen00000000
       - nfs_chus01:/mnt/alfresco1/compartido/chus/volumen00000001
    #command: ["/bin/sh", "-c", "trap : TERM INT; while [ 1 ]; do sleep 15; done & wait"]

  solr1:
    image: 321006660882.dkr.ecr.eu-west-1.amazonaws.com/queres/alfresco-solr4-5.1:5.1.3.2
    hostname: solr1
    restart: always
    environment:
       SOLR_ALFRESCO_HOST: "proxy"
       SOLR_ALFRESCO_PORT: "80"
       SOLR_ALFRESCO_PORT_SSL: "443"
    volumes:
       - index:/opt/index
  proxy:
    image: 321006660882.dkr.ecr.eu-west-1.amazonaws.com/queres/httpd-proxy-alfresco-alpine:latest
    ports:
       - "90:80"
       - "9443:443"
    restart: always
    environment:
       ALFRESCO_MEMBERS: "alfresco1"
       SOLR_MEMBERS: "solr1"

volumes:
  docroot:
    driver: local
  index:
    driver: local
  mysqldb:
    driver: local
  nfs_compartido:
    driver: local
    driver_opts:
      type: nfs
      o: addr=192.168.4.45,rw
      device: ":/home/alfre1/compartido"
  nfs_sscc00:
    driver: local
    driver_opts:
      type: nfs
      o: addr=192.168.4.45,rw
      device: ":/home/alfre1/sscc/volumen00000000"
  nfs_sscc01:
    driver: local
    driver_opts:
      type: nfs
      o: addr=192.168.4.45,rw
      device: ":/home/alfre1/sscc/volumen00000001"
  nfs_sscc02:
    driver: local
    driver_opts:
      type: nfs
      o: addr=192.168.4.45,rw
      device: ":/home/alfre1/sscc/volumen00000002"
  nfs_sscc03:
    driver: local
    driver_opts:
      type: nfs
      o: addr=192.168.4.45,rw
      device: ":/home/alfre1/sscc/volumen00000003"
  nfs_our00:
    driver: local
    driver_opts:
      type: nfs
      o: addr=192.168.4.45,rw
      device: ":/home/alfre1/our/volumen00000000"
  nfs_eoxi_santiago00:
    driver: local
    driver_opts:
      type: nfs
      o: addr=192.168.4.45,rw
      device: ":/home/alfre1/eoxi_santiago/volumen00000000"
  nfs_eoxi_santiago01:
    driver: local
    driver_opts:
      type: nfs
      o: addr=192.168.4.45,rw
      device: ":/home/alfre1/eoxi_santiago/volumen00000001"
  nfs_eoxi_santiago02:
    driver: local
    driver_opts:
      type: nfs
      o: addr=192.168.4.45,rw
      device: ":/home/alfre1/eoxi_santiago/volumen00000002"
  nfs_eoxi_santiago03:
    driver: local
    driver_opts:
      type: nfs
      o: addr=192.168.4.45,rw
      device: ":/home/alfre1/eoxi_santiago/volumen00000003"
  nfs_hula00:
    driver: local
    driver_opts:
      type: nfs
      o: addr=192.168.4.45,rw
      device: ":/home/alfre1/hula/volumen00000000"
  nfs_hula01:
    driver: local
    driver_opts:
      type: nfs
      o: addr=192.168.4.45,rw
      device: ":/home/alfre1/hula/volumen00000001"
  nfs_chus00:
    driver: local
    driver_opts:
      type: nfs
      o: addr=192.168.4.45,rw
      device: ":/home/alfre1/chus/volumen00000000"
  nfs_chus01:
    driver: local
    driver_opts:
      type: nfs
      o: addr=192.168.4.45,rw
      device: ":/home/alfre1/chus/volumen00000001"
